feature(access_logs): make possible to specify an external s3 bucket …
cloudposse/terraform-aws-alb pull request #83
Opened 2021-02-26 14:33 UTC by scream314

…for logs

## what
* Added a new input variable to provide a bucket name for the logging bucket. If the name is provided, the `access_logs` module is skipped.

## why
* To be able to store multiple alb logs in a single bucket.
* To be able to provide an external bucket with a random name.

## references
* closes #77

2021-03-04 12:58 UTC, SweetOps requested changes

2021-03-04 12:58 UTC, SweetOps commented on variables.tf
> +  default     = ""
```suggestion
  default     = null
```

2021-03-04 12:58 UTC, SweetOps commented on main.tf
>    enabled                            = module.this.enabled && var.access_logs_enabled
no reasons to add `count` you can just extend condition in the `enabled`

2021-03-26 18:49 UTC, adamantike commented on main.tf
> +  count = var.access_logs_s3_bucket_id == "" ? 1 : 0
GitHub doesn't allow me to comment on line 83 of this file, but that will have to be changed from:
```
bucket = module.access_logs.bucket_id
```
To:
```
bucket = coalesce(var.access_logs_s3_bucket_id, module.access_logs.bucket_id)
```

2021-03-26 18:50 UTC, adamantike commented
@scream314, let us know if you can week working on this. I can take it, otherwise.

2021-03-27 10:57 UTC, scream314 commented
@adamantike I hope I can address the change requests next week.

2021-04-07 03:20 UTC, adamantike commented
@SweetOps, I think this is ready for another review!

2021-04-07 05:29 UTC, jamengual commented
/test all

2021-04-08 18:23 UTC, lezavala commented
/rebuild-readme

2021-04-10 21:37 UTC, Gowiem commented
/test all

2021-04-10 21:37 UTC, Gowiem approved these changes

2021-04-10 22:40 UTC, merged

2021-04-10 22:41 UTC, Gowiem commented
Thanks @scream314 -- released as `0.31.0`